pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral() // <-- Crucial for the image cropper
        maven { url 'https://jitpack.io' } // <-- Needed for other dependencies
    }
}
rootProject.name = "PixelPlay"
include ':app'
